---
- name: Configure webservers with nginx
  hosts: webservers
  sudo: True
  tasks:
	- name: install nginx
	  yum: name=nginx update_cache=yes
	- name: copy nginx config file
	  copy: src=files/nginx.conf dest=/etc/nginx/conf.d/default
	- name: enable the config
	  file: >
	  	dest=/etc/nginx/conf.d/default
	  	src=/etc/nginx/conf.d/default.conf
	  	state=link
	- name: copy index.html
	  copy: src=files/index.html dest=/usr/share/nginx/html/index.html mode=0644
	- name: restart nginx
	  service: name=nginx state=restarted